### ISSUE TITLE
Chat List Update

### ISSUE THREAD

**Issue by jcaruso001** [jcaruso001/MessagePro#1]
While in the chat message it doesn't update when messages come in.

**Comment by jcaruso001** [comment]
Main chat list updates ever 60 seconds to check for new messages. I've tested and sending from one phone to another has the new incoming messages show up.

**Comment by Emmitts89** [comment]
I cannot verify this because the new users are not syncing so I cannot test whether or not this list is updating.

**Comment by Emmitts89** [comment]
This is working correctly.
