### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Emmitts89** [jcaruso001/MessagePro#10]
The app crashed ALOT on my mom's Galaxy 3. Every time I tried to do something, then it would crash, I'd reopen and then it would work and then crash again. Message always said "MessagePro stopped working". It only crashed once on the Motorola Android I was also using

**Comment by jcaruso001** [comment]
This is not very helpful, you must be specific in your bugs... One you need not only the device but the Android version number so I can look it up in the crash logs. Secondly you need to describe what you were doing to cause the crash. Please open up seprate bugs on each crash and what you were doing along with the android version number.
