### ISSUE TITLE
Send Message Crash

### ISSUE THREAD

**Issue by jcaruso001** [jcaruso001/MessagePro#15]
Logcat after sending a message to emmitt:

01-21 18:16:02.023: E/AndroidRuntime(20224): Process: com.projectcaruso.messagepro, PID: 20224
01-21 18:16:02.023: E/AndroidRuntime(20224): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=-1, data=null} to activity {com.projectcaruso.messagepro/com.projectcaruso.messagepro.MainActivity}: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3714)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3757)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at android.app.ActivityThread.access$1400(ActivityThread.java:170)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at android.os.Looper.loop(Looper.java:146)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at android.app.ActivityThread.main(ActivityThread.java:5635)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at dalvik.system.NativeStart.main(Native Method)
01-21 18:16:02.023: E/AndroidRuntime(20224): Caused by: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at android.database.CursorWindow.nativeGetString(Native Method)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at android.database.CursorWindow.getString(CursorWindow.java:439)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at android.database.CursorWrapper.getString(CursorWrapper.java:114)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at com.projectcaruso.messagepro.MainActivity.getListViewItems(MainActivity.java:147)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at com.projectcaruso.messagepro.MainActivity.onActivityResult(MainActivity.java:247)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at android.app.Activity.dispatchActivityResult(Activity.java:5778)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3710)
01-21 18:16:02.023: E/AndroidRuntime(20224): 	... 11 more

**Comment by jcaruso001** [comment]
Fixed, cursor was used after it was closed by accident.

**Comment by Emmitts89** [comment]
How do I get the details of the errors? When my dad was opening a new message he got "Register Error" at the bottom but he did receive the message.

**Comment by jcaruso001** [comment]
Send screenshots please

**Comment by Emmitts89** [comment]
I have not been able to re-create this error thus far but if it happens again I will take a picture.

**Comment by jcaruso001** [comment]
Thank you.
