### ISSUE TITLE
Samsung Galaxy 3

### ISSUE THREAD

**Issue by Emmitts89** [jcaruso001/MessagePro#16]
This is still not showing the settings button to the right of the "new message" button.

**Comment by jcaruso001** [comment]
This is phone based feature. Depending on the phone it will either show up next to the "+" or it will show up if you press the settings button of your phone. My S4 has the same option, the settings show up on the bottom after pressing the setting button on the phone. Where my tab 4 doesn't have a settings button and it shows up next to the "+" button.
