### ISSUE TITLE
Active Chat List

### ISSUE THREAD

**Issue by jcaruso001** [jcaruso001/MessagePro#2]
Doesn't update when new message comes in.

**Comment by jcaruso001** [comment]
Chat list updates ever 60 seconds to check for new messages when your on an active conversation. I've tested and sending from one phone to another has the new incoming messages show up.

**Comment by Emmitts89** [comment]
This was having a lot of issues tonight. My mom's phone (Michaeleen South) did not have the option to send a message to David South. David sent Michaeleen a message and on Michaeleen's phone it came in under her name. All chats are on one side. All of the messages David sent Michaeleen are on the top, all Michaeleen's responses were on the bottom, so they are not in order. David's phone updates messages if the thread is open, Michaeleen's does not update unless you back out and then open the active thread. 
![img_0558](https://cloud.githubusercontent.com/assets/10625873/6012560/3ff47ce0-ab0f-11e4-89a1-7680c0818409.jpeg)
![img_4550](https://cloud.githubusercontent.com/assets/10625873/6012561/403f891a-ab0f-11e4-9b45-7088115dc41f.JPG)
![img_4551](https://cloud.githubusercontent.com/assets/10625873/6012564/40aeda54-ab0f-11e4-9293-a90dd5027544.JPG)
![img_4552](https://cloud.githubusercontent.com/assets/10625873/6012566/40b1b1c0-ab0f-11e4-879a-22943df42d7b.JPG)
![img_4553](https://cloud.githubusercontent.com/assets/10625873/6012562/40a7dac4-ab0f-11e4-9021-b9c10cfb4e14.JPG)
![img_4556](https://cloud.githubusercontent.com/assets/10625873/6012563/40a93d88-ab0f-11e4-94f4-15cdbd71b1aa.JPG)
![img_4557](https://cloud.githubusercontent.com/assets/10625873/6012565/40b04bb4-ab0f-11e4-922f-a12b3aa7bc37.JPG)
![img_4558](https://cloud.githubusercontent.com/assets/10625873/6012568/40c6c24a-ab0f-11e4-8cd2-d0a0ffdf7fb7.JPG)
![img_4559](https://cloud.githubusercontent.com/assets/10625873/6012567/40c5e50a-ab0f-11e4-8d29-19f1f6a32cd6.JPG)
![img_4761](https://cloud.githubusercontent.com/assets/10625873/6012569/40eb243c-ab0f-11e4-9201-eb5d3be4bb1d.jpeg)

**Comment by jcaruso001** [comment]
I cannot seem to reproduce this issue messaging between myself and my testuser. Open another bug if this continues.
