### ISSUE TITLE
Messaging

### ISSUE THREAD

**Issue by Emmitts89** [jcaruso001/MessagePro#47]
Joe and I both sent each other messages and never received any of them and it has been over 10 minutes.

**Comment by Emmitts89** [comment]
Both of us can see messages from each other in the recap folder in the banner of the thread, but if you open it you cannot see it and it is not in the main message screen.

**Comment by jcaruso001** [comment]
if you message on the main thread afterwards does it correct itself?

**Comment by jcaruso001** [comment]
I was able to reproduce this when i register a new user on a devices where an previous user was registered... looking into the api.

**Comment by jcaruso001** [comment]
The API seemed to not register our devices. Not sure why, but it was only registered the first one (mine) and no others... Should be working now.

**Comment by Emmitts89** [comment]
Joe and I are not receiving messages that we send each other. I have him in my contacts, opened a new thread and it states messages went through but he never received anything.

**Comment by Emmitts89** [comment]
Messaging is so much better! It's faster, sends & receives much quicker.

**Comment by jcaruso001** [comment]
Verified.
