### ISSUE TITLE
Away Profile On

### ISSUE THREAD

**Issue by jcaruso001** [jcaruso001/MessagePro#5]
If an away profile activated, I don't think it needs to be getting messages

**Comment by jcaruso001** [comment]
Please tell me how you want to handle incoming messages while you have a profile active... do you want the incoming messages to even show up until you turn it off or what?

**Comment by Emmitts89** [comment]
I would like to allow incoming messages while the profile is on, I would also like them to remain unread until the user opens the thread. However, the away profile should auto-respond upon receipt of each message.

**Comment by jcaruso001** [comment]
ok after testing it seems away profiles work as wanted, just the unread doesn't. That is addressed under #11
