### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by Emmitts89** [jcaruso001/MessagePro#50]
When I registered new user I clicked register and then it did not take me to the app, I had to back out like it was cancelling what I had just done and then log in and it worked.

**Comment by jcaruso001** [comment]
This has been the way it has always functioned, it has been modified to close out the registration now and come back to the login screen.

**Comment by Emmitts89** [comment]
This is better! After you register and click it, it goes back to the log in screen.

**Comment by jcaruso001** [comment]
Verified
