### ISSUE TITLE
Media

### ISSUE THREAD

**Issue by Emmitts89** [jcaruso001/MessagePro#9]
There was no way for me to attach media, at least that I could find. Pictures, videos, voice messages with the ability to take pics/videos in app

**Comment by jcaruso001** [comment]
This was something I was curious about but you never mentioned when talking about the project. We talked about a "messaging app" be we never talked about media options.

**Comment by Emmitts89** [comment]
We have talked about it a couple times, in the beginning of us working together at the end of August and then a few times since then, but there have been a lot of different things we've spoken about for MessagePro. I went ahead and copy and pasted my email answering your question regarding this on 8/28/14. 

I am unsure if my current chatting functionality is based on XMPP, but will try to get the answer-I just can’t make any promises if he will respond. As for the other questions-

1. I want the messaging functionality to be identical to that of whatsapp/iMessage. Same seamless group messaging, and the ability to remove yourself from a group message-my last developer was working out the kinks with this I believe. Only one conversation thread per contact. In addition, I had previous conversations with my last developer about having it be encrypted like Telegram because they have made the source code public.

2. In a new message the media that needs to be attached is: photo/video(without needing to leave the app-as well as being able to take picture in app)/voice message. You should be able to open links within the app. Not sure if this is important but, currently you are also able to use emoji’s from your Apple keyboard and I would like to keep that. I know some apps make you do in app purchases for that but I don’t want it to function that way. 

Thanks!

Emmitt

**Comment by Emmitts89** [comment]
Does not appear to be any way to attach media still.

**Comment by jcaruso001** [comment]
I marked this as an enhancement, it is not labeled verified. I'm trying to get through  all the issues you currently have open before adding to it.

**Comment by jcaruso001** [comment]
I pushed out the addition of adding photos but the API (the original we built off of) was never built to handle more than that. So we'll have to add the other on another version.

**Comment by jcaruso001** [comment]
Moved to individual issues.
